---
-
  lineinfile:
    create: true
    group: root
    insertafter: EOF
    line: "%LATAGPRO ALL = NOPASSWD:ALL #Defaults    requiretty"
    mode: "0640"
    owner: root
    path: /etc/sudoers.d/001-LATAGPRO
    regexp: "^%LATAGPRO ALL ="
    state: present
    validate: "/usr/sbin/visudo -cf %s"
  name: "Configure visudo file and validate"
  register: visudotest
-
  debug: var=visudotest
  name: "visualizar la variable"
